name: Self-Hosted macOS Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-macos:
    name: Run test on self-hosted macOS
    runs-on: [self-hosted, macOS]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print system info
        run: |
          echo "Running on:"
          uname -a
          sw_vers

      - name: Run a shell test
        run: |
          echo "Testing basic shell command"
          mkdir -p test_dir
          cd test_dir
          echo "hello from self-hosted runner" > testfile.txt
          cat testfile.txt
